version: "3"

services:
  mariadb:
    container_name: mariadb-hive
    image: mariadb:latest
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    container_name: hive-metastore
    build: ./infra/hive.Dockerfile
    image: hive-metastore:latest
    expose:
      - 9083
    depends_on:
      - mariadb

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    ports:
      - 9000:9000
    command: server /data

  spark-node:
    container_name: spark-node
    image: spark-node:latest
    build: ./infra/spark.Dockerfile
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    depends_on:
      - hive-metastore
      - minio
